### ISSUE TITLE
[Feature Request] [Web Client] Disable notification audio

### ISSUE THREAD

**Issue by jimhatesyou** [sgtaziz/WebMessage#10]
I'm sorry if this is the wrong place to put this but there is currently no way to disable the incoming notification audio, or change the sound. Please add something less harsh sounding / ability to disable the audio. I am currently disabling the audio via the sound controller within the Xbox Game Bar in Windows 10.

**Comment by CSab6482** [comment]
Is there a toggle to keep notifications but use the sound? I've been using EarTrumpet as a workaround, but I was just playing a video with audio, and then I received a bunch of dings that interrupted it

**Comment by sgtaziz** [comment]
I mean, you can just set it to system sounds then mute WebMessage notifications through Windows (or whatever OS). This is the most logical way to do it, but technically you can also set an empty .mp3 file. I don't want to add too many options that will crowd Settings, especially when half of them are notification sounds related

**Comment by CSab6482** [comment]
Blank mp3 file it is 😎

**Comment by CSab6482** [comment]
In case anyone else stumbles upon this, I made a blank sound based on the length of [this vide](https://youtu.be/tPEE9ZwTmy0) that you can download [here](https://mega.nz/file/j4tFWSDK#EZ4gedtpjNUVZ8UVU8GJB_c_g-6h-qESvILNlm7-vcQ) or [here](https://www.mediafire.com/file/h12jb0pkjwndviw/blank_sound.mp3/file)
