### ISSUE TITLE
[Bug] Selecting text is interrupted by the tapback menu + is hard to see on sent messages

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#105]
https://user-images.githubusercontent.com/53708281/109856385-6da48780-7c27-11eb-87a2-f437598c9acc.mp4

I was wondering if there could be some kind of text select check in place that would kill any requests to the tapback menu if text is being highlighted. Also, since both the message and highlighted text are blue, could anything be changed to make the selection more visible on sent messages?

**Comment by sgtaziz** [comment]
Fixed
