### ISSUE TITLE
[Bug] Tapbacks behave strangely on links

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#106]
![webmessage](https://user-images.githubusercontent.com/53708281/109888337-55e1f900-7c51-11eb-8b00-c2f7c5585b97.JPG)
![Screenshot 2021-03-03 at 6 48 37 PM](https://user-images.githubusercontent.com/53708281/109888341-567a8f80-7c51-11eb-9207-e6659c0e1ab1.png)

**Comment by sgtaziz** [comment]
![image](https://user-images.githubusercontent.com/5303104/109942666-79568380-7ce5-11eb-9082-cc794d223d4d.jpeg)

This is actually the correct behavior on the receiving end it seems like. Maybe iOS bug? We need to test this better

**Comment by sgtaziz** [comment]
This issue, while still can be buggy, is now fixed. Sending reactions to a link preview (or any balloon) requires a different method. This is now utilized; however, it also means that if the receiving end does not have the balloon (links require a trusted contact to show a preview) the reaction will not show up on their end. This is the behavior from iOS side as well, so we'll call it a day for now. Maybe I'll look into it more once Apple fixes it as well!
