### ISSUE TITLE
[Bug] Apple's proprietary file formats behave strangely sometimes (MOV, possibly HEIC, m4v, caf, m4a, etc.)

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#107]
See [here](https://github.com/iandwelker/smserver/issues/105) and [here](https://github.com/iandwelker/smserver/issues/102#issuecomment-787115174).
The only problem is, I don't know what the solution would be, if any.

**Comment by sgtaziz** [comment]
Added!

**Comment by CSab6482** [comment]
https://github.com/open-imcore/imessage-rest/issues/12#issuecomment-881013862
