### ISSUE TITLE
Favicon is blurry/low resolution in some parts of Windows

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#109]
![WebMessage main](https://user-images.githubusercontent.com/53708281/110244023-d42cec80-7f2a-11eb-95c7-38586a9d6b55.JPG)
![WebMessage Notif](https://user-images.githubusercontent.com/53708281/110244024-d4c58300-7f2a-11eb-9283-89f9eb83bdad.JPG)
![windows theme](https://user-images.githubusercontent.com/53708281/110244028-d727dd00-7f2a-11eb-8a0f-c2ade7ea37ea.JPG)
![WebMessage Notif zoom](https://user-images.githubusercontent.com/53708281/110244031-d8f1a080-7f2a-11eb-93dc-ba75b7e9896b.JPG)
Specifically in the top left of the first two photos, with the zoomed in versions below. I'm not sure where the favicon is stored on the iOS device, but I could fiddle with that and maybe it would help.

**Comment by CSab6482** [comment]
![749CD0EF-6066-4A73-BD28-D6ED9E5783F5](https://user-images.githubusercontent.com/53708281/110244350-51a52c80-7f2c-11eb-873b-f4f9a989e4a3.png)
It looks like I found it, I’ll try messing around with it and update this comment if I find anything that’s helpful

**Comment by CSab6482** [comment]
I think I found the problem. WebMessage only has one 256x256 icon, whereas most other apps have different sized icons for different purposes (16x16, 32x32, 48x48, etc.)
![One size does not fit all](https://user-images.githubusercontent.com/53708281/110246134-5241c100-7f34-11eb-859b-8560961fa5d2.JPG)
Here are Minecraft and BlueBubbles for comparison.
![one size fits all](https://user-images.githubusercontent.com/53708281/110246214-b795b200-7f34-11eb-8721-008196ba27e8.JPG)
![BlueBubbles one size](https://user-images.githubusercontent.com/53708281/110246209-b49ac180-7f34-11eb-8729-a337493eb1ab.JPG)

This was the highest quality 256x256 icon I was able to extract from WebMessage
![WebMessage](https://user-images.githubusercontent.com/53708281/110246357-4d314180-7f35-11eb-8908-83f43fef2844.png)
As well as the 1024x1024
![WebMessage](https://user-images.githubusercontent.com/53708281/110246371-55897c80-7f35-11eb-91d9-239a5e13aec6.png)
I know you have those, I just wanted to share everything I got from the extractor tools

**Comment by sgtaziz** [comment]
I was able to get it a bit better, but frankly just bad design. The small @ symbols in the icon do not scale well, which is a requirement. I'll change it later, but should be better with the next version!
