### ISSUE TITLE
[Feature Request] Contact photos in notifications

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#110]
So I'm not sure what the best way to implement this would be.
![Text-message-alert-notification-with-Actions-button](https://user-images.githubusercontent.com/53708281/110246611-4c4cdf80-7f36-11eb-9bc2-91753bbb2791.jpg)
That is how a notification shows up for an individual macOS chat, and on my Mac with Mojave, in group chat notifications it gives the photo of the person who sent the message. On Big Sur, I'm not sure if this is still what happens or if the group chat photo is what's shown instead,
![Messages-you-were-mentioned-in-this-chat](https://user-images.githubusercontent.com/53708281/110246687-9930b600-7f36-11eb-9f82-dd6a3db7e3cb.png)
There's another sample image I found, so maybe in instances like that, the normal WebMessage icon notification could still work.
![110244024-d4c58300-7f2a-11eb-9283-89f9eb83bdad](https://user-images.githubusercontent.com/53708281/110246698-a8afff00-7f36-11eb-9ac5-a8f9e4a37fa7.jpg)
I was thinking that the WebMessage icon in the top left can always stay, and then the other one just becomes the contact image. And if there is no contact image, should it default to the avatar, or to the WebMessage icon? And, if it is a group chat notification, could it be made so that the top left icon is the group chat photo and the big one is the photo of the individual who sent the message? And then of course there could be problems if either the group chat doesn't have a photo or the contact doesn't.

I'm not sure what the best way to implement this would be, so I think the request needs a little work, but hopefully what I said makes some sense.

**Comment by CSab6482** [comment]
![image](https://user-images.githubusercontent.com/53708281/110247990-e4e65e00-7f3c-11eb-8da5-51e7149b4ffa.png)
So here is how the same notification from a group chat loaded for me on Mojave in both WebMessage and iMessage. I don't have a computer with Big Sur, but I think that would be good to test too.
![Screen Shot 2021-03-07 at 11 26 15 AM](https://user-images.githubusercontent.com/53708281/110248007-ff203c00-7f3c-11eb-97c5-2b21cc8fe3b0.png)
Also, going into the notification details gave me a glitched icon, like in issue #109. I'm not sure if this is specific to me or my OS, or if it affects all of the macOS builds. Also, what is the minimum macOS version required to run the WebMessage client? And the minimum Windows version?

**Comment by CSab6482** [comment]
Thank you for implementing this (and so much more) in the 0.6.1 update! I know this is still a work in progress, especially in macOS, but I have two things to say.
![descriptive](https://user-images.githubusercontent.com/53708281/111038050-f627e280-83f4-11eb-996b-7c5567f41b13.png)
I think the notifications used to display "Tommy loved an image" or "Joseph emphasized [text]". Is this a limitation with a new way of fetching notifications? And for contacts with no contact photo, would it be possible to display their initials avatar? Or is that avatar not actually saved anywhere as an image file? Thank you again for the amazing updates 👍

**Comment by sgtaziz** [comment]
Thank you for the kind words! Having initials is unfortunately not possible at the moment, since the avatar is just CSS/HTML without any images. But I might be able to generate them on the fly, I'll check!
The text is something I overlooked actually, will be fixed in the next update 👍

**Comment by shawnk0723** [comment]
> So I'm not sure what the best way to implement this would be. ![Text-message-alert-notification-with-Actions-button](https://user-images.githubusercontent.com/53708281/110246611-4c4cdf80-7f36-11eb-9bc2-91753bbb2791.jpg) That is how a notification shows up for an individual macOS chat, and on my Mac with Mojave, in group chat notifications it gives the photo of the person who sent the message. On Big Sur, I'm not sure if this is still what happens or if the group chat photo is what's shown instead, ![Messages-you-were-mentioned-in-this-chat](https://user-images.githubusercontent.com/53708281/110246687-9930b600-7f36-11eb-9f82-dd6a3db7e3cb.png) There's another sample image I found, so maybe in instances like that, the normal WebMessage icon notification could still work. ![110244024-d4c58300-7f2a-11eb-9283-89f9eb83bdad](https://user-images.githubusercontent.com/53708281/110246698-a8afff00-7f36-11eb-9ac5-a8f9e4a37fa7.jpg) I was thinking that the WebMessage icon in the top left can always stay, and then the other one just becomes the contact image. And if there is no contact image, should it default to the avatar, or to the WebMessage icon? And, if it is a group chat notification, could it be made so that the top left icon is the group chat photo and the big one is the photo of the individual who sent the message? And then of course there could be problems if either the group chat doesn't have a photo or the contact doesn't.
> 
> I'm not sure what the best way to implement this would be, so I think the request needs a little work, but hopefully what I said makes some sense.

Hey @CSab6482, is your notification working now?
