### ISSUE TITLE
[Bug] Some emojis aren't big

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#113]
These were, in order, 🧑‍🤝‍🧑 👭👫👬 👯👯‍♂️👯‍♀️
<s>Could this be a client specific bug? e.g. Windows doesn't have support for certain emojis</s>
This bug also occurred on my Mac
![small emojis](https://user-images.githubusercontent.com/53708281/110253334-c8a3ea80-7f57-11eb-81bc-7ac4682ffef0.JPG)

**Comment by CSab6482** [comment]
![symbol 1](https://user-images.githubusercontent.com/53708281/110384645-ef335580-802b-11eb-89dc-5a53adc5c355.JPG)
![symbol 2](https://user-images.githubusercontent.com/53708281/110384648-f0648280-802b-11eb-8d99-e523fb7437bc.JPG)
The symbol emojis seem to be affected too

**Comment by sgtaziz** [comment]
New emoji menu should fix this!
