### ISSUE TITLE
[Tweak] Update the Tweak's source code?

### ISSUE THREAD

**Issue by goopy13** [sgtaziz/WebMessage#114]
[github.com/sgtaziz/WebMessage-Tweak](https://github.com/sgtaziz/WebMessage-Tweak) hasn't been updated in a while, however tweak updates have still been coming out. Can we can an update?

**Comment by sgtaziz** [comment]
Woops. I thought the build script was doing this automatically, I'll update it soon 👍

**Comment by sgtaziz** [comment]
Pushed!
