### ISSUE TITLE
[Bug][Client] Pasting images + other files occasionally stops working until a restart

### ISSUE THREAD

**Issue by hsully03** [sgtaziz/WebMessage#116]
After a few image pastes, pasting any file in the clipboard will simply stop working, ctrl+v and right clicking on paste both don't work. You can still paste text, but not images. The only way to fix it is to close it in the tray.

**Comment by sgtaziz** [comment]
New update should be better, let me know if you still experience this 👍

**Comment by CSab6482** [comment]
![once](https://user-images.githubusercontent.com/53708281/111037768-9da41580-83f3-11eb-87fb-c0c7de0bb849.png)
I don't know why this happened, but I had it happen twice. I only dragged one attachment, and seven copies were queued. Quitting and restarting WebMessage fixed the issue. Also, an attachment can only be dragged into the main iMessage line, not the subject text line, but if it's similar to issue #112 I understand.

**Comment by sgtaziz** [comment]
Should be easy to do! Can you create an issue for it?
