### ISSUE TITLE
[Feature Request] [Web Client] Allow closing of a chat / deselection of a chat

### ISSUE THREAD

**Issue by jimhatesyou** [sgtaziz/WebMessage#12]
Once I open the client, I have to have someone's chat window open. Since I have my PC muted, the text will be auto-read and the notification on my phone cleared as soon as it comes in. Once I text someone, I'd like to close the chat so if a new text comes in I will still have the notification on my phone and see that a new text has arrived on the web client as well.

**Comment by gnawh** [comment]
or perhaps marking it read, only if it's in-focus or if you've begun typing.

**Comment by sgtaziz** [comment]
It should only mark it as read in the client, not your phone. Your phone should still have an unread notification based on my testing. Note that if you test this by sending messages to yourself, they will be marked as read automatically.
