### ISSUE TITLE
[Feature Request] Unicode 13.0 emojis

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#122]

**Comment by sgtaziz** [comment]
This is currently a Chromium limitation. See below:

Ah, actually Emoji 13 is still widely unsupported: https://emojipedia.org/emoji-13.0. Both Chrome and Safari latest version don’t support any of these yet. Even iOS doesn’t support them yet (iOS 14.2 hasn’t been released).

Even if the data is known, it usually takes a little longer before browsers support new emoji versions.

__Originally posted by @EtienneLem in https://github.com/missive/emoji-mart/issues/457#issuecomment-714462423__

I will provide an update for it once Emojis 13.0 are more widely supported!

**Comment by CSab6482** [comment]
Ah no problem! Thanks for the explanation and all the new emoji styles

**Comment by CSab6482** [comment]
I'll close this for the time being since it's up to the Emoji Mart people and not you 👍
