### ISSUE TITLE
[Client] [WebMessage] Tweak updated to to v0.6.1 but client didnt

### ISSUE THREAD

**Issue by kingsnissan** [sgtaziz/WebMessage#124]
I also cannot downgrade the tweak to match the client

**Comment by sgtaziz** [comment]
Current latest versions are 0.6.1 for the client, and 0.6.2 for the tweak. What issue are you facing exactly?

**Comment by kingsnissan** [comment]
I have installed both the client and the tweak and they aren’t pairing at all. I’m on the same internet and I entered the port and ip and it isn’t working at all

**Comment by sgtaziz** [comment]
Have you double checked passwords and SSL settings?

**Comment by kingsnissan** [comment]
Yes everything matches it’s just not connecting. When you mean SSL settings do you mean just if it’s enabled or not?

**Comment by sgtaziz** [comment]
Feel free to add me on Discord and we can check it out Aziz#7777
