### ISSUE TITLE
Error code 400 until I get an incoming message

### ISSUE THREAD

**Issue by krutakee** [sgtaziz/WebMessage#138]
When I installed 0.2.4 initially, it listed out all my conversations successfully but it kept giving me error status code 400 whenever I tried to send out a message.  

I tried reinstalling it but it still failed.

Then I got one incoming message then everything started working ok.

It is all good now but I just want to report this issue.

**Comment by sgtaziz** [comment]
The amount of bugs in 0.2.4 was plenty, and current version has fixed most of them. If this still persists or happens again, please let me know! For now, I will be assuming it was fixed.
