### ISSUE TITLE
[Bug] Sometimes WebMessage auto-reads incoming messages when minimized

### ISSUE THREAD

**Issue by ddiggles** [sgtaziz/WebMessage#142]
Title will need clarification:

When WebMessage is minimized, sometimes when I receive a text, it will 'maximize' itself and open the just-received message, and as a result, auto-mark it as read.

When I am in a different room as my computer, this behavior causes me to miss messages / not receive notifications on my phone, because Webmessage will auto-read the message, and as a result, any notification that I receive will be cleared the moment the message is read.  Depending on how quickly this happens, this means I won't know that I received a message on my phone, as there will be no notification, no notification bubble, and no indication that new message(s) are in the app itself.

So, say I'm in the kitchen.  I receive a text, but I never know I received it, because my computer, in another room, will have opened the message and marked it read nearly the instant it was received.

**Comment by sgtaziz** [comment]
This is a known issue currently. I'm doing the best I can to fix any crucial bugs currently and push them by tomorrow, but unfortunately work has been busy and I still have my rewrite-to-a-new-framework roadmap. I will be pushing fixes for this hopefully tomorrow!
