### ISSUE TITLE
[Bug]  With iOS 14.3, iPhone screen has to be on for Windows 10

### ISSUE THREAD

**Issue by krutakee** [sgtaziz/WebMessage#162]
I just upgraded to iOS 14.3 from 14.1.

With iOS 14.1, WebMessage client worked great with Win10 client even if iPhone was locked with screen off.

With iOS 14.3, iPhone's screen has to be on for Win10 client to work. Otherwise, messages are not being loaded in the client and messages won't go out until I turn on iPhone screen.  iPhone can stay locked though.  As soon as I touch iPhone screen to wake it up (or just press power button), it starts working again.

**Comment by CSab6482** [comment]
What jailbreak are you using? If you're using unc0ver, switch to Taurine and see if the bug is the same there. And if you're on Taurine, switch to unc0ver and try it out.

**Comment by krutakee** [comment]
I was using unc0ver 6.1.2.   I could not install Taurine since it would not allow migration.   Instead, I reinstalled WebMessage on my iPhone which fixed the issue.

**Comment by CSab6482** [comment]
> I was using unc0ver 6.1.2. I could not install Taurine since it would not allow migration. Instead, I reinstalled WebMessage on my iPhone which fixed the issue.

Since the issue is fixed, can you close the ticket?
