### ISSUE TITLE
[Client] - how to install

### ISSUE THREAD

**Issue by sfspaulding** [sgtaziz/WebMessage#180]
Hi. Pretty novice at this stuff. Is there a guide on how to actually install the client from GitHub? Preferably a "for dummies" version.

**Comment by ZXSwire3** [comment]
What operating system are you running?

**Comment by sfspaulding** [comment]
Windows 10. Sorry, should've clarified.

**Comment by ZXSwire3** [comment]
no worries, if you go to the main GitHub page on the right you should see a button that says releases, just click that and then download the 'WebMessage-Setup-0.7.0.exe' file and run the installer. Once you install it you just need to enter your info from your iOS device.

**Comment by sfspaulding** [comment]
Ahh. I was looking at the actual, not the "release". I'm all set now, thank you kind stranger.
