### ISSUE TITLE
[Feature Request] Hotkeys/Shortcuts

### ISSUE THREAD

**Issue by gnawh** [sgtaziz/WebMessage#25]
Either built in conversation hotkeys similar to Mac (ctrl + shift + [ or ]), or custom user-defined hotkeys.

Next/Previous conversation: ctrl + shift [ or ]
New Conversation: ctrl + n

.. That might be it tbh lol

**Comment by sgtaziz** [comment]
Shouldn't be too bad to add. I'll see what I can do!

**Comment by sgtaziz** [comment]
Command/Control + 1/2/3/4/5/6/7/8/9 for the first x chats in list
Command/Control + N for new message
