### ISSUE TITLE
Client tunnels to physically connected iDevice over other iDevice with WebMessage installed

### ISSUE THREAD

**Issue by jiznon** [sgtaziz/WebMessage#28]
First off, love the app! 

Now, I've been trying to figure out why the client hasn't been showing any text threads since 0.2.7+. I narrowed it down to the client -- it is assuming the iPad mini (gen 1, iOS 9.3.5, jailbroken) I have plugged in as a secondary display is the iDevice I have WebMessage running on. 

Manually inputting the IP of my iPad Pro with WebMessage installed doesn't make a difference. Only unplugging the iPad mini from my computer allows the client to establish a connection to the correct device. This causes the tunneling status indicator to turn red, and fall back to the IP that's in the field.

So for me, red is good, strangely enough.

Is it possible to manually disable tunneling to prevent this issue? Or perhaps a check by the client to confirm the daemon is running on the plugged in device?

Thanks!

**Comment by sgtaziz** [comment]
Fixed with commit 541c8a1
