### ISSUE TITLE
[Feature Request] iOS 14 Inline Replies?

### ISSUE THREAD

**Issue by goopy13** [sgtaziz/WebMessage#29]
I have no idea if this is possible or how long it would take but it would be amazing if we had this. Love the stuff so far, keep it up!

**Comment by jiznon** [comment]
What is "iOS 14 replies feature"? Do you mean inline replies?

**Comment by jaigup** [comment]
Yeah the inline replies. It would also be nice if we could get [mentions](https://support.apple.com/en-us/HT211303) but I think that would be harder and isn't that important anyway.

**Comment by sgtaziz** [comment]
I would love to try and add support for this. However, I don't have an iOS 14 device to test on. My current device is iOS 13, and I'm essentially just ensuring all the functions and hooks I'm using exist on other versions. If I get my hands on an iOS 14 device that's jailbroken, I will definitely add this to my to-do list!

**Comment by sgtaziz** [comment]
I will be closing all iOS 14 feature requests for the time being so I can focus on my current road map. I have them tagged though, and will reopen them once I can better test iOS 14 features 👍
