### ISSUE TITLE
[Feature Request] No support for displaying subject line text

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#31]
![No Subject Line](https://user-images.githubusercontent.com/53708281/107441707-aeffb680-6b03-11eb-9c69-02592b318836.JPG)
![IMG_0318](https://user-images.githubusercontent.com/53708281/107441712-b1621080-6b03-11eb-92cb-40bd87ea3748.PNG)
Can I also make this a request to add the feature to be able to send subject line text from the client, or should I open a separate ticket?

Great job on this tweak by the way, it really reminds me of the Remote Messages tweak a lot. I also find it inspiring that you built this tweak in between time with a full time job. I've always wanted to get in to dev work but have put it off because of school and other things. I definitely don't know enough programming to build a tweak or app just yet, but I hope to get there one day.

**Comment by sgtaziz** [comment]
I will add subject support on my to-do list 👍

**Comment by CSab6482** [comment]
![Invalid date](https://user-images.githubusercontent.com/53708281/108879560-63eba600-75cf-11eb-88c2-4864747bd1c0.JPG)
I'm not sure what causes this bug, but I think it's related to subject line text. There was no subject line text around this particular message, but the first time I saw a "Read Invalid date" was after a message with subject line text in it

**Comment by sgtaziz** [comment]
Actually it is an unrelated bug that I already fixed, but I'm taking my time pushing it as I don't want the same thing that happened last time to happen again :~)

**Comment by sgtaziz** [comment]
6ad309540009680933536ae0cd50e125b670c9a1 😎
