### ISSUE TITLE
[Feature Request] Send an image/video/attachment first when sending it with a text caption

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#33]
Basically a copy and paste of my issue posted [here](https://github.com/iandwelker/smserver/issues/84)/[here](https://github.com/BlueBubblesApp/BlueBubbles-Desktop-App/issues/144)

**Comment by sgtaziz** [comment]
With JavaScript, sorting is handled by the filesystem when selecting multiple files. However, with the ability to drag & drop files and even with copy & paste (although copy & paste only supports 1 file at a time due to, once again, HTML/JavaScript limitation) you can order it however you want.

Just make sure you select the files in the order you want, then drag & drop them. The order shown in the attachments preview is in fact the order in which the client will send the messages. These features will be available in the next release.

**Comment by CSab6482** [comment]
![Pic 1](https://user-images.githubusercontent.com/53708281/107979825-3c705a00-6f8d-11eb-8ae7-32aa90726d8c.JPG)
Yes, the files send in order, I just mean the text sends before the file does (though it shows up correctly in the WebMessage client)

Above is a photo of my queued message in WebMessage, then how it shows up in WebMessage and on iOS
![Pic 2](https://user-images.githubusercontent.com/53708281/107979912-5ad65580-6f8d-11eb-9dcc-5fb8bba1f0ca.JPG)
![Pic 3](https://user-images.githubusercontent.com/53708281/107979920-5dd14600-6f8d-11eb-8930-a7268185b483.png)

**Comment by sgtaziz** [comment]
That's just the way WebMessage client vs SMS app work. I think showing the text after the attachment makes more sense when it's one message. SMS app does the opposite. It's all one message, and I can change it if needed. However, there is no way to let others see the text message after the attachments if it's sent as one message. You will notice the same functionality from your iOS device as well

**Comment by CSab6482** [comment]
https://user-images.githubusercontent.com/53708281/107985656-7b57dd00-6f98-11eb-8704-54412688dc57.MP4

![WebMessage](https://user-images.githubusercontent.com/53708281/107985617-68dda380-6f98-11eb-89a8-632d64b9fe4b.JPG)
![SMServer](https://user-images.githubusercontent.com/53708281/107985618-68dda380-6f98-11eb-935e-c7fea74229c8.JPG)
![BlueBubbles](https://user-images.githubusercontent.com/53708281/107985614-68450d00-6f98-11eb-8992-e6aa272becd0.jpg)
Do you mean that when sending multiple attachments from iOS with a text caption, the text caption displays first?

**Comment by sgtaziz** [comment]
Strange. On my device it's different, I'll definitely look into this 👍

**Comment by sgtaziz** [comment]
I was able to fix this issue; unfortunately, it is a pretty big update that I will be pushing out. So it's going to take a few days until release just so I can iron out most of the bugs 👍
