### ISSUE TITLE
[Feature Request] Ability to paste or drag images into the chat, rather than only uploading saved files

### ISSUE THREAD

**Issue by wonkieinc** [sgtaziz/WebMessage#36]
I need to share a lot of images from my PC via iMessage for work. It would be awesome if I did not have to first save these images first and could just copy/paste screenshots from Snip & Sketch directly into the relevant message thread

**Comment by jaigup** [comment]
#11

**Comment by sgtaziz** [comment]
Duplicate as mentioned by @jaigup
