### ISSUE TITLE
[Feature Request] Web/Link previews

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#38]

**Comment by CSab6482** [comment]
![jut](https://user-images.githubusercontent.com/53708281/109594753-58bddc00-7ae1-11eb-90bb-e9170dc471db.JPG)
I've mentioned it before, but I just wanted to log it here that sent URLs stick out a little to the right.

**Comment by CSab6482** [comment]
Is it safe to close this?

**Comment by sgtaziz** [comment]
Woops, yes!

**Comment by CSab6482** [comment]
![WebMessage link](https://user-images.githubusercontent.com/53708281/110242895-13a50a00-7f26-11eb-91c6-b16c87f5e880.JPG)
The top link was sent from my Mac, and the bottom one was sent from WebMessage. The play button only shows up on YouTube links sent from WebMessage (I think, may have to test further).

**Comment by CSab6482** [comment]
Could it also be possible to check whether or not the conversation is with a saved contact? If not, then no request is made for web previews, and the conversation loads the same in WebMessage as it does on the host device? Or would it be too difficult to check for a saved contact with things like iCloud sync and stuff like that?

**Comment by sgtaziz** [comment]
@CSab6482 I am having a hard time replicating this issue.

As far as the checking for contacts, this isn't really needed at all. WebMessage does not bother to check if previews will be enabled, or even make any requests to the link itself. The data of the link preview comes directly from what your phone interpreted it as.
I did notice that sometimes, your iOS messages will show a normal link while WebMessage will show the full link. This isn't WebMessage's fault, or that it is creating requests on behalf of the user. iOS seems to always create the request, even if the sender is not a saved contact, and saves it in the database. However, it simply decides not to show it in the Messages app itself. WebMessage will read the database and find that the preview information exists, and continues along.
Obviously, the whole point of not creating requests if the sender is not a contact is security. Unfortunately though, this (minor) security issue comes from iOS, and not WebMessage :(

**Comment by CSab6482** [comment]
The issue may be Windows only, but it has been consistent for me. I'll test further on my Mac. And thank you for the explanation!

**Comment by sgtaziz** [comment]
I tested it on both actually with no luck :( if you can send me the exact link that is failing, I can try to take a better look!

**Comment by CSab6482** [comment]
For me, it is all YouTube links. Only those sent from WebMessage work properly. I'll send you a few.
