### ISSUE TITLE
Keyboard shortcuts steal from other applications

### ISSUE THREAD

**Issue by kswartz26** [sgtaziz/WebMessage#39]
There needs to be an ability to either toggle the keyboard shortcuts and/or limit them to only working when the WebMessage window has focus. Otherwise, it prevents these same shortcuts from working in other apps.

Trying to use emacs without Control-N, for example, is pretty hard....

**Comment by sgtaziz** [comment]
Huh. Definitely not intended to be globally applied. I'll get to it ASAP, thank you 👍

**Comment by sgtaziz** [comment]
Fixed with 9a828a3c3957024cfcfad434dbe580e8a3a3b2f9
