### ISSUE TITLE
WebMessage app not appearing in Windows Notifications & Actions

### ISSUE THREAD

**Issue by Zgrill2** [sgtaziz/WebMessage#40]
Windows does not show in windows notifications as an app but in the notification options there are 3 toggles saying you can turn off all notifications for this app. Due to this, if you turn off notification settings from the toast, there is no way to turn it back on.

No WebMessage appearing in notification settings
![three_toggles](https://user-images.githubusercontent.com/9122236/107732325-136a7380-6cc6-11eb-9e0f-502d16c16be5.png)

Toast notification appears and has option to turn off notifications as seen in screenshot below.
![image](https://user-images.githubusercontent.com/9122236/107732713-026e3200-6cc7-11eb-9540-d03acbec9dbe.png)

**Comment by sgtaziz** [comment]
1cfa43bd66b2197a1378f5b857e0a4472b14a5ea
