### ISSUE TITLE
[Bug] Conversations list does not have most recent message

### ISSUE THREAD

**Issue by gnawh** [sgtaziz/WebMessage#41]
Conversations pane will not display most recent message. I think it goes out of sync once you reconnect. The actual conversation has most updated message, but is not shown in the list.

**Comment by sgtaziz** [comment]
With my testing, the conversation pane is always updated given that the client is connected at the time you sent/received the text. Unfortunately, if it loses connection then you need to refresh by going to settings and hitting save. Is this what you meant by this issue?

**Comment by sgtaziz** [comment]
The latest update does provide some improvements with conversation pane syncing. Feel free to let me know if I need to reopen this 👍

**Comment by gnawh** [comment]
Yeah, while spending a lot of time troubleshooting my phone i rrspring often, which causes me to disconnect and reconnect and also miss messages. I'll let you know how it goes today!

Also, adprivacyd must have tweak injection enabled.. that's what would cause wm to crash or not start properly. Weird. I went a little too crazy disabling tweak injection 😅
