### ISSUE TITLE
Messages sent from non webmessage node do not sync

### ISSUE THREAD

**Issue by Zgrill2** [sgtaziz/WebMessage#42]
Messages sent from a separate device not running webmessage but with the same iCloud account do not show up on Desktop Client. In this picture the iPhone is running the webmessage server and when sending messages from the iPad, the iPhone shows the sent messages while the desktop client does not. 

![1](https://user-images.githubusercontent.com/9122236/107889785-e6df7300-6ee2-11eb-9f4a-0afbb3a5c12f.jpeg)

**Comment by sgtaziz** [comment]
At the current time, WebMessage works by intercepting messages your are sending through the SMS app. I am sure there is a different way to hook this, but this is known logic at the time. I will try to find different ways to hook messages and let you know if there is any progress 👍

**Comment by Zgrill2** [comment]
SMS Server syncs properly, perhaps their codebase is a good place to get some ideas. Also, when exiting and then rebooting webmessgae client on windows 10 desktop all messages sync and appear. Hopefully one of these two ideas helps you figure out the proper hooks.

**Comment by sgtaziz** [comment]
That's just because WebMessage doesn't try to load everything every time. You can go to settings and press save to refresh manually

**Comment by sgtaziz** [comment]
I fixed this issue using different methods of hooking texts. Unfortunately, it is a pretty big update that I will be pushing out. So it's going to take a few days until release just so I can iron out most of the bugs 👍
