### ISSUE TITLE
Option to leave messages unread until typing/sending

### ISSUE THREAD

**Issue by wonkieinc** [sgtaziz/WebMessage#43]
Messages appear to be marked read if a chat is left open in the app in the background, I'd really like to avoid this without having to select my own number chat each time I switch app

**Comment by sgtaziz** [comment]
If the app is in the background, it will not mark messages as read. It makes them as read if the window is in focus and the chat is in focus. Also, you can close out of the chat using the top right button if needed.

Are you sure it is marking as read when not in focus? Based on my testing, this never happens

**Comment by wonkieinc** [comment]
When the most foreground window on one of my monitors, even if not the active window, I am quite sure of it

Could be related to me using Delay Read Receipts (iOS 10) on my phone itself

I would still much prefer manual/when typing/when sending Read Receipts however if at all possible, even if I am mistaken here

Thankyou

**Comment by wonkieinc** [comment]
Additionally II just tried closing out of chats with this top right button and it does nothing for me

**Comment by sgtaziz** [comment]
It doesn't close the chat?

**Comment by wonkieinc** [comment]
No, has no function at all for me

**Comment by wonkieinc** [comment]
Updated to latest version today, please see https://imgur.com/a/ZTLOL2Q

**Comment by sgtaziz** [comment]
Strange. I'll look into it 👍

**Comment by sgtaziz** [comment]
899c3eed9edb4e7491ff72e5381dc9c3bdcc5b3c

**Comment by wonkieinc** [comment]
Thankyou this is a fantastic app, better with each update
