### ISSUE TITLE
Backup messages

### ISSUE THREAD

**Issue by mason1171** [sgtaziz/WebMessage#44]
Can it be made possible to automatically or manually backup messages and attachments to the client connected?  I doubt this would be possible but could a restoration feature also be looked into please? Thank you

**Comment by sgtaziz** [comment]
Technically, it is possible. However, it would not be practical at all.

Backing up messages to the client would not serve much of a benefit. On top of that, it can create confusion, as the backed up messages would not be up-to-date with the messages available through your phone. There is a feature that caches messages during runtime, but it is not saved; therefore, not backed up. Perhaps you mean something different?

In terms of attachments, you can save any attachment through the client to your computer using the available download button

**Comment by CSab6482** [comment]
Maybe something like [this](https://twitter.com/K3Y_VAN/status/1312433725234270208)?

**Comment by sgtaziz** [comment]
I mean, definitely possible. It would be equivalent to printing a page since it's all in HTML. Can you confirm @mason1171?

**Comment by mason1171** [comment]
I was thinking a real-time backup solution where you view so the html idea could work

Jared D

**Comment by sgtaziz** [comment]
Do you want a backup or a an export of your messages?

Difference would be is that a backup is usually made to be restored. An export would just be a PDF or similar with the messages that you can view/share. Kind of like a screenshot, but a really long one with multiple pages

**Comment by mason1171** [comment]
Preferably something like this if possible, a sort of combination of the two features
http://www.3u.com/news/articles/5378/how-to-search-message-in-3utools-backup-viewer

**Comment by sgtaziz** [comment]
Ah I see. Definitely possible, but I don't think it would be in the scope of this project. Though you are able to do it manually pretty easily by just making a copy of your sms.db file (/var/mobile/Library/sms.db).

**Comment by mason1171** [comment]
I understand. Would the export feature be possible with attachments?

**Comment by sgtaziz** [comment]
Attachments are also saved on your device, so yeah! They're in your /var/library/SMS/Attachments directory. Though it's not really sorted in any specific way, but making a copy of both will ensure all your messages and attachments are backed up

**Comment by mason1171** [comment]
Ok, cool. Thanks
