### ISSUE TITLE
[Bug] Cannot display a message that is just a space

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#48]
(Copied from the SMServer ticket for convenience)
I was talking to someone and they were telling me about how something left them speechless, so they sent me a message that was just " ", which displays as a small blank blue bubble on iOS (the more spaces, the longer the bubble). This message didn't display on my Android phone with the BlueBubbles app, or any of my other iMessage forwarding apps, so I sat there confused waiting to receive a message only to check my iPhone and see that it was a blank. Of all the apps with this issue, SMServer was the only one that allowed me to send a blank, and SMServer and WebMessage both displayed a timestamp for the blank message.
![Blank WebMessage](https://user-images.githubusercontent.com/53708281/108304371-e90d3000-7175-11eb-9f14-678a3525e8aa.JPG)
![Blank iOS](https://user-images.githubusercontent.com/53708281/108304378-ead6f380-7175-11eb-928a-ceed1a891e79.PNG)
See issues [here](https://github.com/iandwelker/smserver/issues/90), [here](https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/786), and [here](https://github.com/BlueBubblesApp/BlueBubbles-Desktop-App/issues/155)

**Comment by sgtaziz** [comment]
Actually, this was on purpose. I did not realize iOS allows you to send blank messages, it's usually an accepted standard to not allow sending of messages that only contain spaces, as it is treated as an empty message. Pretty easy fix though, and will be coming with the next update!

**Comment by CSab6482** [comment]
![Spaces](https://user-images.githubusercontent.com/53708281/108765661-11a07b80-7522-11eb-9c08-a05d6023b0d9.JPG)
I have an update on this issue. The first blank message has 4 spaces in it. The second one that doesn't show up only has one space, the one below that has two, and the one below that has 12. It looks like only messages with two or more spaces show up.

**Comment by CSab6482** [comment]
Fixed!
