### ISSUE TITLE
Tapbacks have trouble with one message that has multiple attachments

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#51]
This is a similar issue to [this SMServer ticket](https://github.com/iandwelker/smserver/issues/81) and [this BlueBubbles ticket](https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/542). I have two videos below, one showcasing the expected behavior on iOS, and the other showcasing the graphical bug in WebMessage. Thank you for all the fixes and changes 👍

https://user-images.githubusercontent.com/53708281/108585868-d3843b80-7318-11eb-910d-245a4bf79034.mp4

https://user-images.githubusercontent.com/53708281/108585872-d8e18600-7318-11eb-984b-5e0a66ee9e6d.mp4

**Comment by sgtaziz** [comment]
I actually noticed this as well. I'll see what I can do

**Comment by sgtaziz** [comment]
4abacd9 😎

**Comment by CSab6482** [comment]
This is dope. Thank you so much

**Comment by CSab6482** [comment]
![Screen Shot 2021-03-01 at 12 40 53 PM](https://user-images.githubusercontent.com/53708281/109536576-e5d64600-7a8b-11eb-86c5-2abd15ef04ac.png)
![mismatch ios](https://user-images.githubusercontent.com/53708281/109536583-e7a00980-7a8b-11eb-83b1-e7f3726e9b3e.png)
![mismatch t](https://user-images.githubusercontent.com/53708281/109536589-e8d13680-7a8b-11eb-9ebe-842adb3c4915.JPG)
I sent this tapback from my Mac, and it shows up correctly on my WebMessage server, but not in the client. Restarting WebMessage from either device did not fix it.

**Comment by CSab6482** [comment]
Okay I think I have more info on this, someone sent me an image with no caption or anything, and I used my Mac to apply a tapback on that image. Nothing showed up in WebMessage, but I have a feeling that if the image was sent with a caption, the tapback would have shown up on the caption. Next time, I’ll apply a tapback with my iPad or iPhone to see if it’s just my Mac that causes this.

**Comment by CSab6482** [comment]
![bug](https://user-images.githubusercontent.com/53708281/110990566-7bea5600-8341-11eb-95e5-adc0b643b058.png)
![PNG image](https://user-images.githubusercontent.com/53708281/110990580-7e4cb000-8341-11eb-90c0-895fb34372fa.png)
Here is another bug that I just got related to this issue

**Comment by CSab6482** [comment]
> ![Screen Shot 2021-03-01 at 12 40 53 PM](https://user-images.githubusercontent.com/53708281/109536576-e5d64600-7a8b-11eb-86c5-2abd15ef04ac.png)
> ![mismatch ios](https://user-images.githubusercontent.com/53708281/109536583-e7a00980-7a8b-11eb-83b1-e7f3726e9b3e.png)
> ![mismatch t](https://user-images.githubusercontent.com/53708281/109536589-e8d13680-7a8b-11eb-9ebe-842adb3c4915.JPG)
> I sent this tapback from my Mac, and it shows up correctly on my WebMessage server, but not in the client. Restarting WebMessage from either device did not fix it.

I've attached an image below which is a reverse of this issue. I applied a tapback from my Mac on the text caption (which can be seen in WebMessage's conversation history) but nothing shows up graphically
![tapback thingy](https://user-images.githubusercontent.com/53708281/111925164-13f0e980-8a7e-11eb-9ced-18a5f871f8c3.png)

**Comment by CSab6482** [comment]
> ![bug](https://user-images.githubusercontent.com/53708281/110990566-7bea5600-8341-11eb-95e5-adc0b643b058.png)
> ![PNG image](https://user-images.githubusercontent.com/53708281/110990580-7e4cb000-8341-11eb-90c0-895fb34372fa.png)
> Here is another bug that I just got related to this issue

Regarding the Thanos message, I was able to get this information from MyMessage. p0 should have a 2003 acknowledgment/tapback and p1 should have a 2004 acknowledgment/tapback. Both are from the same person.

{
"id": "D3DBDAD8-5EEE-4D72-ADB7-20A74501706D",
"fromMe": true,
"isTypingMessage": false,
"description": "We'll show up and he'll be like",
"flags": 1081349,
"fileTransferIDs": [
"72D48466-A535-4C93-AA78-6791A8AB53F1"
],
"chatID": "chat526745548997352517",
"time": 1615577622383.0002,
"timeRead": 0,
"isSOS": false,
"timeDelivered": 0,
"isAudioMessage": false,
"isCancelTypingMessage": false,
"items": [
{
"type": "attachment",
"payload": {
"metadata": {
"size": {
"width": 500,
"height": 255
},
"id": "72D48466-A535-4C93-AA78-6791A8AB53F1",
"filename": "AE5727AE-29A7-4E84-B537-17AFD35FEB41.gif",
"uti": "com.compuserve.gif",
"mime": "image/gif"
},
"id": "p:0/D3DBDAD8-5EEE-4D72-ADB7-20A74501706D",
"chatID": "chat526745548997352517",
"transferID": "72D48466-A535-4C93-AA78-6791A8AB53F1",
"fromMe": true,
"time": 1615577622383.0002
}
},
{
"type": "text",
"payload": {
"chatID": "chat526745548997352517",
"fromMe": true,
"parts": [
{
"type": "text",
"string": "We'll show up and he'll be like"
}
],
"id": "p:1/D3DBDAD8-5EEE-4D72-ADB7-20A74501706D",
"time": 1615577622383.0002,
"text": "We'll show up and he'll be like",
"acknowledgments": [
{
"chatID": "chat526745548997352517",
"sender": "my friend's email",
"associatedID": "p:1/D3DBDAD8-5EEE-4D72-ADB7-20A74501706D",
"id": "am:F0716C13-6871-4286-A4A6-3CF3FB0B25CD",
"fromMe": false,
"time": 1615577636093.2012,
"acknowledgmentType": 2003
}
]
}
}
],
"service": "iMessage",
"timePlayed": 0,
"sender": "e:my email",
"isDelivered": false
}

Originally posted in https://github.com/iandwelker/smserver/issues/81#issuecomment-813494130

**Comment by CSab6482** [comment]
This one isn't that bad, the only issue is that the stacked emphasis only shows 2 instead of 3, but it's the best one of the bunch
![WebMessage Obama](https://user-images.githubusercontent.com/53708281/114328043-7a12de80-9b09-11eb-9172-cff851b1ebc8.png)
![Obama iOS](https://user-images.githubusercontent.com/53708281/114076603-d4474180-9874-11eb-81b3-e9300226529c.png)

**Comment by CSab6482** [comment]
There are two things I'd like to say about this one. Firstly, when enabling privacy mode, can it be set up so that the tapbacks still show up? This screenshot is pasted together with the screenshot that didn't have privacy mode turned on so that I could show the tapbacks. Now, [just like in SMServer](https://github.com/iandwelker/smserver/issues/81#issuecomment-817414111), the tapbacks display in the correct order, but the images do not. MyMessage has the images in the correct order, but one of the tapbacks is missing (see [here](https://github.com/open-imcore/imcore.react/issues/8#issuecomment-817379826))
![WebMessage 3](https://user-images.githubusercontent.com/53708281/114328115-99aa0700-9b09-11eb-81a7-96ca6f5b5078.png)
![PNG image (1)](https://user-images.githubusercontent.com/53708281/114322787-17f9af80-9af0-11eb-8e09-842c2a635662.png)

**Comment by CSab6482** [comment]
Here is another situation with one message that has parts of it that are both text and attachments. Below is how the conversation shows up on iOS
![iOS](https://user-images.githubusercontent.com/53708281/118409211-3b67cb00-b657-11eb-817d-f4c142f7aa0d.png)
and in WebMessage
![WebMessage](https://user-images.githubusercontent.com/53708281/118411338-0a40c800-b662-11eb-8ef9-7ffff9d45ba7.png)
The text shows in the proper order in MyMessage, and below is the message information that I copied from MyMessage.
> {
  "id": "28935DBA-A57E-485E-9442-10FBAD3A3C95",
  "fromMe": true,
  "isTypingMessage": false,
  "description": "Here is a message that has images intermittently scattered throughout it",
  "flags": 1085445,
  "fileTransferIDs": [
    "49CA2847-DF32-4D66-9857-7163EE1FCE49",
    "9C606BB6-2443-4101-A55A-8E2610D08988",
    "00A6CB41-165B-43B8-881F-59D725515B36"
  ],
  "chatID": "*recipient*",
  "time": 1620776404411,
  "timeRead": 0,
  "isSOS": false,
  "timeDelivered": 1620776405263.5593,
  "isAudioMessage": false,
  "isCancelTypingMessage": false,
  "items": [
    {
      "type": "text",
      "payload": {
        "id": "p:0/28935DBA-A57E-485E-9442-10FBAD3A3C95",
        "chatID": "*recipient*",
        "parts": [
          {
            "type": "text",
            "string": "Here is a message"
          }
        ],
        "fromMe": true,
        "time": 1620776404411,
        "text": "Here is a message"
      }
    },
    {
      "type": "attachment",
      "payload": {
        "metadata": {
          "size": {
            "width": 200,
            "height": 200
          },
          "id": "49CA2847-DF32-4D66-9857-7163EE1FCE49",
          "filename": "IMG_1752.png",
          "uti": "public.png",
          "mime": "image/png"
        },
        "id": "p:1/28935DBA-A57E-485E-9442-10FBAD3A3C95",
        "chatID": "*recipient*",
        "transferID": "49CA2847-DF32-4D66-9857-7163EE1FCE49",
        "fromMe": true,
        "time": 1620776404411
      }
    },
    {
      "type": "text",
      "payload": {
        "id": "p:2/28935DBA-A57E-485E-9442-10FBAD3A3C95",
        "chatID": "*recipient*",
        "parts": [
          {
            "type": "text",
            "string": "that has images"
          }
        ],
        "fromMe": true,
        "time": 1620776404411,
        "text": "that has images"
      }
    },
    {
      "type": "attachment",
      "payload": {
        "metadata": {
          "size": {
            "width": 200,
            "height": 200
          },
          "id": "9C606BB6-2443-4101-A55A-8E2610D08988",
          "filename": "IMG_3897.png",
          "uti": "public.png",
          "mime": "image/png"
        },
        "id": "p:3/28935DBA-A57E-485E-9442-10FBAD3A3C95",
        "chatID": "*recipient*",
        "transferID": "9C606BB6-2443-4101-A55A-8E2610D08988",
        "fromMe": true,
        "time": 1620776404411
      }
    },
    {
      "type": "text",
      "payload": {
        "id": "p:4/28935DBA-A57E-485E-9442-10FBAD3A3C95",
        "chatID": "*recipient*",
        "parts": [
          {
            "type": "text",
            "string": "intermittently scattered"
          }
        ],
        "fromMe": true,
        "time": 1620776404411,
        "text": "intermittently scattered"
      }
    },
    {
      "type": "attachment",
      "payload": {
        "metadata": {
          "size": {
            "width": 200,
            "height": 200
          },
          "id": "00A6CB41-165B-43B8-881F-59D725515B36",
          "filename": "IMG_4390.png",
          "uti": "public.png",
          "mime": "image/png"
        },
        "id": "p:5/28935DBA-A57E-485E-9442-10FBAD3A3C95",
        "chatID": "*recipient*",
        "transferID": "00A6CB41-165B-43B8-881F-59D725515B36",
        "fromMe": true,
        "time": 1620776404411
      }
    },
    {
      "type": "text",
      "payload": {
        "id": "p:6/28935DBA-A57E-485E-9442-10FBAD3A3C95",
        "chatID": "*recipient*",
        "parts": [
          {
            "type": "text",
            "string": "throughout it"
          }
        ],
        "fromMe": true,
        "time": 1620776404411,
        "text": "throughout it"
      }
    }
  ],
  "service": "iMessage",
  "timePlayed": 0,
  "sender": "*me*",
  "isDelivered": true
}
