### ISSUE TITLE
[Bug] Version 0.4.5, All conversations turn blue and won't load

### ISSUE THREAD

**Issue by QwopJoans** [sgtaziz/WebMessage#52]
Updated to version 0.4.5 from 0.3.2, downloaded both through the client and then uninstalled and downloaded and reinstalled from Github. Downgraded to 0.4.1 then 0.4.0 and issue persisted, downgraded back to 0.3.2 and it stopped.

All conversations load in client; once a conversation is selected, all conversations gain a blue background, the loading icon is displayed in the thread view, and no messages or contacts are loaded.

**Comment by sgtaziz** [comment]
Make sure you update the tweak as mentioned in the release notes. Some big changes were pushed so your client and tweak should be on the same version.

I try to usually have the version numbers matching tweak and client side. If you notice a 0.1 jump (0.3.x -> 0.4.x) it will most likely mean you have to make sure both the tweak and client are updated.

Let me know if you face any issues after the update!

**Comment by QwopJoans** [comment]
That fixed, thanks! Is it possible to get a reminder to update the tweak if you use the client to update? I didn't read the release notes before clicking the update button in the client and only skimmed them as I downloaded it from Github.

**Comment by sgtaziz** [comment]
No worries! I actually do have a plan to have the client warn you when you're using an outdated version, so will be coming soon :)
