### ISSUE TITLE
[Bug] Contacts scrambled in conversation list with tapback details

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#54]
I have two chats in which my friend Gene put a tapback on a message, but in WebMessage it says that Zach added the tapback. I have another chat where Patrick put a tapback on an image, but WebMessage says Tyler put the tapback on the image (the correct tapback does show though, e.g. loved, emphasized, etc.)

**Comment by CSab6482** [comment]
Also I don't want to open a ticket for this in case I'm just doing something wrong and this is an easy fix, but when I'm in macOS mode on the client, clicking the red button doesn't do anything

**Comment by sgtaziz** [comment]
Fixed with latest update
