### ISSUE TITLE
[Feature Request] iOS 14 group chat photos

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#55]

**Comment by sgtaziz** [comment]
I unfortunately do not have an iOS 14 device to test on. However, I will be more than happy to look into it in the future!

**Comment by CSab6482** [comment]
> I unfortunately do not have an iOS 14 device to test on. However, I will be more than happy to look into it in the future!

I'd be happy to test out these features on my iOS 14 device, as well as asking Janshai how he got these features working in SMServer

**Comment by sgtaziz** [comment]
I can look at his source code and get a pretty clear idea. However, it would make debugging a nightmare, especially since I can't really see the UI components in the client as they won't be populated with my iOS 13 device.

I do plan on getting an older device and install checkra1n on it later though, so will definitely be happening at some point 👍

**Comment by sgtaziz** [comment]
I will be closing all iOS 14 feature requests for the time being so I can focus on my current road map. I have them tagged though, and will reopen them once I can better test iOS 14 features 👍

**Comment by CSab6482** [comment]
https://github.com/iandwelker/smserver/commit/master#diff-23f782692c889c4ae88bf07ebee31076401238d5c5debd0dbbc69b46d85555eeR565
This was all I was able to find from SMServer's release with group chat photos

**Comment by CSab6482** [comment]
![group chat photos](https://user-images.githubusercontent.com/53708281/110243206-63380580-7f27-11eb-9cca-4a294ec591f6.JPG)
So here, from top to bottom, I have an individual chat, two group chats, and then two individual chats. It looks like the individual chats are perfect circles, but the group chats are a bit edgy and cut off on the left side. Let me know if this picture and explanation make sense
