### ISSUE TITLE
[Feature Request] iOS 14 pinned chats

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#56]

**Comment by sgtaziz** [comment]
https://github.com/sgtaziz/WebMessage/issues/55#issuecomment-782873888

**Comment by sgtaziz** [comment]
I will be closing all iOS 14 feature requests for the time being so I can focus on my current road map. I have them tagged though, and will reopen them once I can better test iOS 14 features 👍

**Comment by CSab6482** [comment]
https://github.com/iandwelker/smserver/blob/v0.5.0/src/SMServer/Obj.h#L26
https://github.com/iandwelker/smserver/blob/v0.5.0/src/SMServer/html/chats.html#L237
https://github.com/iandwelker/smserver/blob/v0.5.0/src/SMServer/html/style.css#L193
Here's everything from SMServer's release with pinned chats that I was able to find

**Comment by iandwelker** [comment]
https://github.com/iandwelker/libsmserver/blob/master/Tweak.xm#L231-L258 -- this is really the most important part for getting the pinned chats
