### ISSUE TITLE
[Feature Request] Some kind of message for messages that cannot be displayed in WebMessage

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#57]
Here is an example with digital touch in WebMessage, SMServer, and BlueBubbles
![digital touch WebMessage](https://user-images.githubusercontent.com/53708281/108608460-fe13da00-7394-11eb-8075-52b28eabb370.JPG)
![digital touch SMServer](https://user-images.githubusercontent.com/53708281/108608465-ffdd9d80-7394-11eb-90cc-ab1271fe5aec.JPG)
![digital touch BlueBubbles](https://user-images.githubusercontent.com/53708281/108608466-01a76100-7395-11eb-8274-fc8a764437f1.jpg)

**Comment by sgtaziz** [comment]
All unsupported message types now show a warning
