### ISSUE TITLE
[(Graphical) Feature Request] Two exclamation marks on the emphasis

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#59]
If this is just silly then close it but I was wondering if it would be possible or even a good thing to implement.

**Comment by sgtaziz** [comment]
Definitely possible. Just don't have it implemented currently because I am using FontAwesome, which doesn't have the double exclamation marks. I can stack two next to each other if needed though!

**Comment by CSab6482** [comment]
![iMessage Thumbs Down](https://user-images.githubusercontent.com/53708281/108636538-e94a4b80-7453-11eb-9c7b-2d4d2e8db275.png)
![WebMessage Thumbs Down](https://user-images.githubusercontent.com/53708281/108636539-eb140f00-7453-11eb-89fa-82aa8beee5ff.JPG)
Also the thumbs down is mirrored from what it looks like on iOS and macOS

**Comment by CSab6482** [comment]
![Tapback Menu](https://user-images.githubusercontent.com/53708281/110248142-9c7b7000-7f3d-11eb-9cc7-f5e960543c14.png)
Would it also be possible to have the tapback menu open from the right instead of the left? On macOS, this causes the tapbacks that are already stacked to disappear though, so did you choose to put it on the left to have visibility of both the menu and what people have already reacted with?

**Comment by sgtaziz** [comment]
The tapback menu placement is intended. I just feel like it's less clutter-y that way, though moving it definitely is possible. I will close this issue as it relates to the exclamation marks. If it is really something you think would be preferable, feel free to open another request and we can discuss it more!
