### ISSUE TITLE
[Bug] [Web Client] Group chats have double names

### ISSUE THREAD

**Issue by emiyl** [sgtaziz/WebMessage#6]
![image](https://user-images.githubusercontent.com/31181801/106289120-c788ea80-6240-11eb-9f49-55787265ea81.png)

On iOS, the name of this chat shows up as "Jamie & Max".

Client Version: Windows 0.2.4
iOS Version/JB: 13.7 Odyssey
Tweak Version: 0.2.4

**Comment by sgtaziz** [comment]
Good find! I'll push a fix to this with the next update
