### ISSUE TITLE
[Bug] Cannot send attachments without a text caption on version 0.4.5-0.4.8 (Windows client)

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#60]
I attempted to drag and drop an attachment to send, and that sent my phone into safe mode, so then I tried by just manually attaching it but that also sent me into safe mode.
I've attached two crash logs below
[WebMessage drag and drop.txt](https://github.com/sgtaziz/WebMessage/files/6016961/WebMessage.drag.and.drop.txt)
[WebMessage manual attach.txt](https://github.com/sgtaziz/WebMessage/files/6016962/WebMessage.manual.attach.txt)

**Comment by Joe00** [comment]
Exact same problem for me

**Comment by sgtaziz** [comment]
I will fix it soon, apologies!

**Comment by sgtaziz** [comment]
Does this always happen? I can't seem to replicate it. What if you include a text with the attachment?

**Comment by Joe00** [comment]
yes it always happens, with or without text doesn't make a difference

**Comment by Joe00** [comment]
a friend with also an ipad 6 on ios 14.4 doesn't have this problem

**Comment by Joe00** [comment]
ok now it works but only when adding a text. on my friends one the same

**Comment by CSab6482** [comment]
https://github.com/iandwelker/smserver/issues/96
I did not test with/without a caption in WebMessage, but I will do so later today and let you know my results

**Comment by sgtaziz** [comment]
Try out the latest update and let me know how it goes.

**Comment by CSab6482** [comment]
[WebMessage Image no caption crash (Springboard).txt](https://github.com/sgtaziz/WebMessage/files/6017973/WebMessage.Image.no.caption.crash.Springboard.txt)
I'm still getting the bug on the updated version, however I verified that sending with a caption does not cause a crash. Also, all the dates in my chats now display as January 19, 1970

**Comment by sgtaziz** [comment]
I definitely accidentally uploaded an older version of the tweak... one sec lol

**Comment by sgtaziz** [comment]
Give tweak version 0.4.7 a shot

**Comment by CSab6482** [comment]
[WebMessage (Springboard) 0.4.7 crash no caption image.txt](https://github.com/sgtaziz/WebMessage/files/6017992/WebMessage.Springboard.0.4.7.crash.no.caption.image.txt)
Unfortunately it still crashes

**Comment by sgtaziz** [comment]
darn it. This is definitely iOS 14 specific from what I can tell, though unfortunately don't have much time left to debug today. I'll try to get it tomorrow!

**Comment by Joe00** [comment]
Yeah I cAn confirm. Still crashes..

**Comment by sgtaziz** [comment]
This should be covered now. Can you confirm?

**Comment by sgtaziz** [comment]
Confirmed by @CSab6482. Thanks for the help you two 😊
