### ISSUE TITLE
Time/date is incorrect

### ISSUE THREAD

**Issue by Claranon** [sgtaziz/WebMessage#66]
I updated to the latest release and noticed that the time/date for the messages is showing up incorrectly.

Screenshot (cropped for privacy):

![timedate](https://user-images.githubusercontent.com/55359663/108711684-b5b70200-74e3-11eb-9fd0-05af2d38d038.png)

**Comment by sgtaziz** [comment]
Make sure to update your tweak as well 👍

**Comment by Claranon** [comment]
Sorry, when I checked Cydia earlier today I didn’t see an update but now it’s there and everything is fine again. Thank you so much for all your work on this!
