### ISSUE TITLE
[Feature Request] Make enter to send toggleable

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#69]
This
request
is
so
that
I
can
send
messages
that
look
like
this
https://github.com/iandwelker/smserver/issues/100

**Comment by sgtaziz** [comment]
What about Shift+Enter? It's common practice to have Enter as send, and Shift+Enter to create a new line

**Comment by CSab6482** [comment]
Oh cool. I'd never heard of that before since my email app does it by making enter a new line and ctl+enter send. It works though so I'll close the issues. Thank you for teaching me!

**Comment by sgtaziz** [comment]
test

**Comment by sgtaziz** [comment]
The Ctrl+Enter comes into play when it's a multi-line field that is made for typing long messages, where multiple paragraphs are more common than a single line (such as texting)

Any messaging client, or really anything that has quick text entries that are more often than not 1 liners, will always use Shift+Enter for a new line, and Enter to send. Unfortunately, I really don't think I will be implementing this as it is the intended behavior

**Comment by CSab6482** [comment]
Ah okay, no worries then thank you for the explanation 👍

**Comment by CSab6482** [comment]
Shift+enter does not work in the subject line

**Comment by sgtaziz** [comment]
@CSab6482 another limitation from not having emojis enabled. Will be coming with the reworked emoji menu!
