### ISSUE TITLE
[Bug] Tapbacks take precedence over sent messages in the conversation preview

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#71]
Here's an example situation:

Person 1: Hey CSab6482, how are you doing!

Me: Hi Person 1, I'm doing okay thankfully, how are you?

Person 1 loved "Hi Person 1, I'm doing okay thankfully, how are you?"

Me: Hey, I found some old GameCube controller adapters in my closet. Would you want to play Smash sometime soon?

So in the conversation preview, instead of my most recent message about the GameCube controllers showing up, the tapback notification would be what shows up. Let me know if any more information/testing is needed

**Comment by sgtaziz** [comment]
Does this persist when you reload?

**Comment by CSab6482** [comment]
Not to out myself as a moron but how do I reload?

**Comment by sgtaziz** [comment]
Yeah you got it! Either that or relaunching the client.

I can probably make it so clicking the indicator will refresh👍

**Comment by CSab6482** [comment]
Okay, I got a few tests in and it looks like when sending the tapback and message from WebMessage, it works okay.
![Bug](https://user-images.githubusercontent.com/53708281/108918438-5f3ee600-75ff-11eb-8682-42562eff2e5c.JPG)
Here is an example with a tapback and text that I sent from my Mac. The text came after the tapback but the tapback is what loads in the preview

**Comment by sgtaziz** [comment]
On it 🤓

**Comment by sgtaziz** [comment]
i have been trying to replicate this for 4 years and i have no clue how. I only have a mac client that I can test with, so maybe its something iPad specific?

**Comment by CSab6482** [comment]
Honestly same, and my iPad crash too. Let me dm you my iMessage handle so we can test it

**Comment by CSab6482** [comment]
Unable to replicate, likely a tapback lag from my Android phone
