### ISSUE TITLE
Clicking on a conversation in the client causes all conversations to be highlighted

### ISSUE THREAD

**Issue by rafaelcespino** [sgtaziz/WebMessage#72]
When I click a conversation to open it on the Windows client, every single conversation on the left side of the screen turns blue as if I clicked all of them at once to open them. The right side of the screen gets stuck on the loading icon and I can't open any conversations to read or reply to them. This is what it looks like after I click one conversation to open it: https://ibb.co/9cxY15j (I added the white box myself to keep my chats private). I have tried reinstalling and even downgrading my version, but the problem does not go away.

**Comment by sgtaziz** [comment]
Make sure you update your tweak on your iOS device
