### ISSUE TITLE
[Feature Request] Searching for emojis

### ISSUE THREAD

**Issue by ZXSwire3** [sgtaziz/WebMessage#73]
I personally use a few emojis a decent amount, such as 🤔. It would be nice to be able to search for emojis directly instead of having to look through a list of emojis. It would also be cool if you could go a step forward and do it like discord does where you just type it into the chat and start the emoji with a ":" and then type whatever the name is and then end with another ":" so for example ":thinking:" would do the 🤔 emoji
![image](https://user-images.githubusercontent.com/19944156/108944342-653cc300-760f-11eb-8757-bb094690e2ae.png)

**Comment by sgtaziz** [comment]
Amazing suggestion! I'll see what I can do.

**Comment by CSab6482** [comment]
If you're on Windows, you can do this by pressing the windows key and period button, then simply typing 👀

**Comment by ZXSwire3** [comment]
I honestly forget about this all the time, but I still think it would be useful to have it built in natively in the client so you have the same functionality across other OS's

**Comment by CSab6482** [comment]
I agree, our Linux friends could definitely use this. I just wanted to offer a temporary fix for you in the meantime 😃

**Comment by ZXSwire3** [comment]
thank you for the tip, it actually does help a decent amount even if it is just hopefully temporary 🙂

**Comment by CSab6482** [comment]
@ZXSwire3 does the latest update work for you?

**Comment by ZXSwire3** [comment]
@CSab6482 yes, it works pretty well, I think it would still be nice to either have some sort of key bind to bring up the emoji window, and have it automatically select the search box so that you can quickly add an emoji without moving your hands from the keyboard, or have some sort of symbol that you can write before searching for the emoji like previously mentioned about how discord does it. Either way would be a nice quality of life improvement.

**Comment by CSab6482** [comment]
https://user-images.githubusercontent.com/53708281/110273940-af249200-7f9b-11eb-9083-7fa794ee541b.mp4

**Comment by sgtaziz** [comment]
This was done purposefully. I am recoding the entire emoji picker, and didn't want to get into the headache of implementing it in subject line of it's gonna get reworked anyways. Coming soon™️

**Comment by CSab6482** [comment]
https://user-images.githubusercontent.com/53708281/110870372-4a6a7f80-829a-11eb-9cbb-13c94d5d7ad5.mp4

Here is another emoji menu bug I encountered
