### ISSUE TITLE
[Feature Request] Native Emoji Toggle

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#74]
Here is an example in BlueBubbles Desktop
![Emoji Apple](https://user-images.githubusercontent.com/53708281/109060938-00877400-76b4-11eb-9b79-75b5f5931814.JPG)
![Native 1](https://user-images.githubusercontent.com/53708281/109060947-02513780-76b4-11eb-8a18-141fb8fd20a6.JPG)
![Native 2](https://user-images.githubusercontent.com/53708281/109060951-041afb00-76b4-11eb-8d78-eeed40f04c03.JPG)
![Emoji Native](https://user-images.githubusercontent.com/53708281/109060956-054c2800-76b4-11eb-9b9d-19e7a5098b98.JPG)

**Comment by sgtaziz** [comment]
Actually, I had native Apple-style emojis by default. I removed that later though as I didn't want to be on bad terms with Apple's license, which doesn't really allow you to use Apple emojis on non-Apple systems. This is why WhatsApp and Slack for example no longer show Apple emojis in their apps.

**Comment by CSab6482** [comment]
Yes, I think WebMesaage uses FontAwesome for the emojis, correct me if I'm wrong though. What I meant was for a toggle to turn those emojis off in favor of my system's (Windows) native emojis, like in the last photo

**Comment by sgtaziz** [comment]
Ah, understood, my bad! That is definitely possible. I currently use Twemoji, which is Twitter's opensource emoji project. System emojis unfortunately are not always updated with Apple's always-changing emoji library, but a toggle is definitely possible 😄
