### ISSUE TITLE
[Bug] Sending group chat messages from other devices while WebMessage is open causes my phone to respring and/or reload WebMessage

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#75]
It doesn't respring into safe mode since WebMessage still reloads perfectly fine, but this happens when I have WebMessage open on my computer (using an iPhone as a server), and I am texting from my iPad. I can confirm it is a respring because I have to open SMServer again to get it running
[Crash 1 Bug 75.txt](https://github.com/sgtaziz/WebMessage/files/6039156/Crash.1.Bug.75.txt)
[Crash 2 Bug 75.txt](https://github.com/sgtaziz/WebMessage/files/6039157/Crash.2.Bug.75.txt)
[Crash 3 Bug 75.txt](https://github.com/sgtaziz/WebMessage/files/6039158/Crash.3.Bug.75.txt)

**Comment by sgtaziz** [comment]
All these crash logs essentially say the webserver isn't running, which is strange. I'll have to do some testing and get back to you

**Comment by CSab6482** [comment]
It could be a coincidence then. I wasn't doing anything on my WebMessage server device, but I had the client open on my computer

**Comment by sgtaziz** [comment]
Closing this issue for now as we can't really get more info on it. If it keeps crashing or snowballs into a worse bug, feel free to reopen!

**Comment by sgtaziz** [comment]
Let me know if you can replicate this with 0.4.9-2. Should be covered now I believe

**Comment by sgtaziz** [comment]
Fixed with 0.5.0
