### ISSUE TITLE
[Feature Request] Ability to see all attachments

### ISSUE THREAD

**Issue by lectrician7** [sgtaziz/WebMessage#79]
Ability to see all attachments from each message thread like in the iMessage app on the phone.

**Comment by sgtaziz** [comment]
This should be already supported. Can you elaborate?

**Comment by lectrician7** [comment]
In the iMessage app on iOS you can select the contacts name then "info". This brings up a thumbnail of all the attachments (photos, videos, links) ever sent in that thread. If this is already implemented I apologize, but I can't find that ability in the pc client.

**Comment by sgtaziz** [comment]
Gotcha 👍 this is already planned and mentioned in #46

Support will be coming!
