### ISSUE TITLE
[Feature Request] Nuanced Subject field request to send subject line text as regular text when there is no text in the main body (I'm sorry for the headache)

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#80]
Thank you so much for adding support for subject line text viewing+sending, it's amazing! Here is what happens in WebMessage when attempting to send a text with text in the subject body but none in the main body
![No text](https://user-images.githubusercontent.com/53708281/109366927-b264a300-7862-11eb-8141-3f0c3ace580a.JPG)
and below is a video I used for a similar ticket in SMServer (linked [here](https://github.com/iandwelker/smserver/issues/85))

https://user-images.githubusercontent.com/53708281/109366940-bc86a180-7862-11eb-9754-c18da0a7be36.mp4

**Comment by CSab6482** [comment]
Update - The error 400 prevents any text entry until you quit and restart the app, and it also occurs when clicking the send button when there is no text or attachments to send

**Comment by sgtaziz** [comment]
This is strange. This should already work, and works fine on my device. When sending a subject with no text, the subject will be treated as text instead. There is already checks in place to make sure there is data to send before sending it. I will do some more testing and get back to you

**Comment by sgtaziz** [comment]
Found the issue. An update will be pushed soon!

**Comment by sgtaziz** [comment]
ee295bc
