### ISSUE TITLE
[Bug] Tapbacks on images are dangling | Client and Server 0.5.0

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#81]
![dangling](https://user-images.githubusercontent.com/53708281/109367255-9a415380-7863-11eb-905e-0a9fe061b870.JPG)
![Dislodged](https://user-images.githubusercontent.com/53708281/109372209-5f94e680-7876-11eb-8234-64029f117c5e.JPG)
This affects all images, sent or received, and in both group and individual chats

**Comment by sgtaziz** [comment]
ee295bc
