### ISSUE TITLE
[Bug] Read receipts and delivered receipts cannot be displayed at the same time

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#83]
So if I sent a message that was read and then a few seconds later I send another message that hasn't been read yet, the message on the bottom should have a delivered receipt while the one on top has a read receipt, but instead, neither show up in WebMessage

Update - Sometimes the delivered tag shows up, but both do not show up  at once

**Comment by sgtaziz** [comment]
ee295bc
