### ISSUE TITLE
[Feature Request] Display who sent a message in a group chat in the windows notifications

### ISSUE THREAD

**Issue by ZXSwire3** [sgtaziz/WebMessage#84]
![image](https://user-images.githubusercontent.com/19944156/109374411-fd35e900-7869-11eb-9f1e-e82c7c65b650.png)
![image](https://user-images.githubusercontent.com/19944156/109374436-23f41f80-786a-11eb-9cee-67ca5e6de46b.png)
I'm honestly not super sure if this is something that you could implement, but it would be nice to be able to see who the message is from in a group chat when windows displays the notifications.

**Comment by sgtaziz** [comment]
ee295bc
