### ISSUE TITLE
[Feature Request] [Client] Contact photos next to received messages in a group chat (and toggle for individual chats)

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#87]

**Comment by sgtaziz** [comment]
Added, alongside initial-based avatars for contacts

**Comment by CSab6482** [comment]
Can there also be a toggle to enable this in individual chats? I like seeing my friends' photos

**Comment by CSab6482** [comment]
<img width="295" alt="PNG image" src="https://user-images.githubusercontent.com/53708281/110249260-5c1ef080-7f43-11eb-8a33-1229bcd89568.png">
![ZT](https://user-images.githubusercontent.com/53708281/110249261-5c1ef080-7f43-11eb-861f-fef841c9f2fc.JPG)
For contacts with three and more names, can the initials in the avatar use the last name in the string?

**Comment by CSab6482** [comment]
> Can there also be a toggle to enable this in individual chats? I like seeing my friends' photos

To prevent the toggles from getting cluttered, maybe a third sub-menu for conversations could be created
![Conversation](https://user-images.githubusercontent.com/53708281/110532173-8363f200-80ea-11eb-8660-1162e40dc2bc.JPG)
This is how BlueBubbles does it on Android
![Menu 1](https://user-images.githubusercontent.com/53708281/110532216-8bbc2d00-80ea-11eb-95da-121b6c8b8e12.jpg)
![Menu 2](https://user-images.githubusercontent.com/53708281/110532225-8eb71d80-80ea-11eb-95ba-bb3ebd5a9e67.jpg)
So things like the subject line, contact photos, and maybe even colors for avatars without a photo or bubble/conversation theming. I'm not requesting all those features, I just wanted to help with the presentation since I remember you said you didn't want to add more toggles for muting notification sounds.

**Comment by sgtaziz** [comment]
@CSab6482 great idea! Can you create a new issue?
