### ISSUE TITLE
[Feature Request] On-screen confirmation that a file was downloaded successfully

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#91]
![File confirmation](https://user-images.githubusercontent.com/53708281/109439983-8716bb00-79fe-11eb-8032-c2f7bc50bc29.JPG)
This is how the software for my physics homework does it for example, but browsers also have the thing pop up at the bottom, and I think either would work

**Comment by sgtaziz** [comment]
physics gives me ptsd

**Comment by sgtaziz** [comment]
The confirmation is a bit more subtle, but it will show as a progress bar in the bottom bar icon. Note that the file does start downloading before you select the download location
