### ISSUE TITLE
[Bug] Delivered tags don't show for messages from other devices

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#92]
I sent the message with the green circle from WebMessage, and the one with the yellow circle from my Mac. There was no delivered tag, and this may be a problem with iOS (I didn't check my WebMessage server device, so I can do further testing)
![sent from another device](https://user-images.githubusercontent.com/53708281/109440174-42d7ea80-79ff-11eb-9ebb-41a7c82ffe6a.JPG)

**Comment by sgtaziz** [comment]
This is known unfortunately. Delivered receipts don't get notified when sending through other devices.

**Comment by CSab6482** [comment]
Oh hmm. Would it be possible to detect that the message came from another device, and then if a match is found on the host device, then a delivered tag shows? Or is something like that too inefficient?

**Comment by sgtaziz** [comment]
Unfortunately there is no distinct property that proves a message came from a different device. If it shows up from one device to another (both being your iMessage ID, not recipient and sender), the message was delivered. If it fails to deliver, it won't show up at all. Though for some reason, the delivered timestamp is for some reason is not updated at all. I'll have to really dig deep into this, but it will probably be a while :(

**Comment by sgtaziz** [comment]
Unfortunately, it seems like there isn't a good way to do this currently without brute-forcing :( I'll keep an eye out though and reopen this if I find something.

**Comment by CSab6482** [comment]
This works in MyMessage, I just tested it 😳
