### ISSUE TITLE
[Feature Request] More descriptive notifications/chat previews for attachments

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#95]
Currently, the conversation preview just says "Attachment" when an attachment or group of attachments were the last things sent, and the notification is blank. Here is a mockup I made with some examples of what showed up on my iOS conversation preview on the right.
![Screenshot 2021-02-28 222449](https://user-images.githubusercontent.com/53708281/109449552-c6e99c80-7a16-11eb-952e-ed2c3563a293.png)
Here are some sample notifications from iOS and BlueBubbles Android
![notification](https://user-images.githubusercontent.com/53708281/109451668-edf69d00-7a1b-11eb-8e42-22d8ab98cd35.png)
On iOS, it's a movie in the notification, but a video in the conversation preview. Interesting.
![bluebubbles android](https://user-images.githubusercontent.com/53708281/109451672-ef27ca00-7a1b-11eb-8dce-424802f1e196.jpg)

**Comment by sgtaziz** [comment]
I haven't added this because it's a minor convenience that will require more logic, queries, and processing power. I will look into it, but if it seems too much for a small thing I might abandon it

**Comment by sgtaziz** [comment]
I think I will be closing this for now, since it seems a bit too complicated for a small thing. If I find a better way to handle it, I will reopen this!

**Comment by CSab6482** [comment]
![attachment](https://user-images.githubusercontent.com/53708281/111407828-aa05c800-86aa-11eb-88bb-564d3651fc2f.png)
I'm not sure if this is intended behavior or a fluke, but I got a notification telling me that a message contained an attachment on version 0.6.1

**Comment by sgtaziz** [comment]
Yes, showing "Attachment" was added recently. Though this issue talks more about what kind of attachments I thought?

**Comment by CSab6482** [comment]
> Yes, showing "Attachment" was added recently. Though this issue talks more about what kind of attachments I thought?

All improvements are good improvements 🥳
